name: 巴哈每日簽到2

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run cron at 00:10 UTC+8
    - cron:  '10 16 * * *'

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: execute py script # run the run.py to get the latest data
        run: |
          python main.py
        env:
          UID: ${{ secrets.UID }}
          PASSWD: ${{ secrets.PASSWD }}
